////////////////////////////////////////////////////////////////////////////////
//
//  YOUR QUILL
//
////////////////////////////////////////////////////////////////////////////////

#include "command/SizeCommand.ipp"

#include "command/size/AddMaxSize1DCommand.ipp"
#include "command/size/AddMaxSize2DCommand.ipp"
#include "command/size/AddMaxSize3DCommand.ipp"
#include "command/size/AddMaxSize4DCommand.ipp"
#include "command/size/AddMaxSizeWDCommand.ipp"
#include "command/size/AddMaxSizeXDCommand.ipp"
#include "command/size/AddMaxSizeYDCommand.ipp"
#include "command/size/AddMaxSizeZDCommand.ipp"
#include "command/size/AddMinSize1DCommand.ipp"
#include "command/size/AddMinSize2DCommand.ipp"
#include "command/size/AddMinSize3DCommand.ipp"
#include "command/size/AddMinSize4DCommand.ipp"
#include "command/size/AddMinSizeWDCommand.ipp"
#include "command/size/AddMinSizeXDCommand.ipp"
#include "command/size/AddMinSizeYDCommand.ipp"
#include "command/size/AddMinSizeZDCommand.ipp"
#include "command/size/AddSize1DCommand.ipp"
#include "command/size/AddSize2DCommand.ipp"
#include "command/size/AddSize3DCommand.ipp"
#include "command/size/AddSize4DCommand.ipp"
#include "command/size/AddSizeWDCommand.ipp"
#include "command/size/AddSizeXDCommand.ipp"
#include "command/size/AddSizeYDCommand.ipp"
#include "command/size/AddSizeZDCommand.ipp"
#include "command/size/MultiplyMaxSize1DCommand.ipp"
#include "command/size/MultiplyMaxSize2DCommand.ipp"
#include "command/size/MultiplyMaxSize3DCommand.ipp"
#include "command/size/MultiplyMaxSize4DCommand.ipp"
#include "command/size/MultiplyMaxSizeDCommand.ipp"
#include "command/size/MultiplyMaxSizeWDCommand.ipp"
#include "command/size/MultiplyMaxSizeXDCommand.ipp"
#include "command/size/MultiplyMaxSizeYDCommand.ipp"
#include "command/size/MultiplyMaxSizeZDCommand.ipp"
#include "command/size/MultiplyMinSize1DCommand.ipp"
#include "command/size/MultiplyMinSize2DCommand.ipp"
#include "command/size/MultiplyMinSize3DCommand.ipp"
#include "command/size/MultiplyMinSize4DCommand.ipp"
#include "command/size/MultiplyMinSizeDCommand.ipp"
#include "command/size/MultiplyMinSizeWDCommand.ipp"
#include "command/size/MultiplyMinSizeXDCommand.ipp"
#include "command/size/MultiplyMinSizeYDCommand.ipp"
#include "command/size/MultiplyMinSizeZDCommand.ipp"
#include "command/size/MultiplySize1DCommand.ipp"
#include "command/size/MultiplySize2DCommand.ipp"
#include "command/size/MultiplySize3DCommand.ipp"
#include "command/size/MultiplySize4DCommand.ipp"
#include "command/size/MultiplySizeDCommand.ipp"
#include "command/size/MultiplySizeWDCommand.ipp"
#include "command/size/MultiplySizeXDCommand.ipp"
#include "command/size/MultiplySizeYDCommand.ipp"
#include "command/size/MultiplySizeZDCommand.ipp"
#include "command/size/SetMaxSize1DCommand.ipp"
#include "command/size/SetMaxSize2DCommand.ipp"
#include "command/size/SetMaxSize3DCommand.ipp"
#include "command/size/SetMaxSize4DCommand.ipp"
#include "command/size/SetMaxSizeWDCommand.ipp"
#include "command/size/SetMaxSizeXDCommand.ipp"
#include "command/size/SetMaxSizeYDCommand.ipp"
#include "command/size/SetMaxSizeZDCommand.ipp"
#include "command/size/SetMinSize1DCommand.ipp"
#include "command/size/SetMinSize2DCommand.ipp"
#include "command/size/SetMinSize3DCommand.ipp"
#include "command/size/SetMinSize4DCommand.ipp"
#include "command/size/SetMinSizeWDCommand.ipp"
#include "command/size/SetMinSizeXDCommand.ipp"
#include "command/size/SetMinSizeYDCommand.ipp"
#include "command/size/SetMinSizeZDCommand.ipp"
#include "command/size/SetSize1DCommand.ipp"
#include "command/size/SetSize2DCommand.ipp"
#include "command/size/SetSize3DCommand.ipp"
#include "command/size/SetSize4DCommand.ipp"
#include "command/size/SetSizeWDCommand.ipp"
#include "command/size/SetSizeXDCommand.ipp"
#include "command/size/SetSizeYDCommand.ipp"
#include "command/size/SetSizeZDCommand.ipp"

