////////////////////////////////////////////////////////////////////////////////
//
//  YOUR QUILL
//
////////////////////////////////////////////////////////////////////////////////

#include "event/SpatialEvent.ipp"
#include "event/spatial/AABB1Event.ipp"
#include "event/spatial/AABB2Event.ipp"
#include "event/spatial/AABB3Event.ipp"
#include "event/spatial/AABB4Event.ipp"
#include "event/spatial/MaxSize1DEvent.ipp"
#include "event/spatial/MaxSize2DEvent.ipp"
#include "event/spatial/MaxSize3DEvent.ipp"
#include "event/spatial/MaxSize4DEvent.ipp"
#include "event/spatial/MinSize1DEvent.ipp"
#include "event/spatial/MinSize2DEvent.ipp"
#include "event/spatial/MinSize3DEvent.ipp"
#include "event/spatial/MinSize4DEvent.ipp"
#include "event/spatial/Orientation2Event.ipp"
#include "event/spatial/Orientation3Event.ipp"
#include "event/spatial/Position1DEvent.ipp"
#include "event/spatial/Position1MEvent.ipp"
#include "event/spatial/Position2DEvent.ipp"
#include "event/spatial/Position2MEvent.ipp"
#include "event/spatial/Position3DEvent.ipp"
#include "event/spatial/Position3MEvent.ipp"
#include "event/spatial/Position4DEvent.ipp"
#include "event/spatial/Position4MEvent.ipp"
#include "event/spatial/Scale1DEvent.ipp"
#include "event/spatial/Scale2DEvent.ipp"
#include "event/spatial/Scale3DEvent.ipp"
#include "event/spatial/Scale4DEvent.ipp"
#include "event/spatial/Size1DEvent.ipp"
#include "event/spatial/Size2DEvent.ipp"
#include "event/spatial/Size3DEvent.ipp"
#include "event/spatial/Size4DEvent.ipp"
