////////////////////////////////////////////////////////////////////////////////
//
//  YOUR QUILL
//
////////////////////////////////////////////////////////////////////////////////

#include "event/SpatialEvent.ipp"
#include "event/spatial/AABB1Event.ipp"
#include "event/spatial/AABB2Event.ipp"
#include "event/spatial/AABB3Event.ipp"
#include "event/spatial/AABB4Event.ipp"
#include "event/spatial/MaxSize1DEvent.ipp"
#include "event/spatial/MaxSize2DEvent.ipp"
#include "event/spatial/MaxSize3DEvent.ipp"
#include "event/spatial/MaxSize4DEvent.ipp"
#include "event/spatial/MinSize1DEvent.ipp"
#include "event/spatial/MinSize2DEvent.ipp"
#include "event/spatial/MinSize3DEvent.ipp"
#include "event/spatial/MinSize4DEvent.ipp"
#include "event/spatial/Orientation2DEvent.ipp"
#include "event/spatial/Orientation3DEvent.ipp"
#include "event/spatial/Position1DEvent.ipp"
#include "event/spatial/Position2DEvent.ipp"
#include "event/spatial/Position3DEvent.ipp"
#include "event/spatial/Position4DEvent.ipp"
#include "event/spatial/Scale1DEvent.ipp"
#include "event/spatial/Scale2DEvent.ipp"
#include "event/spatial/Scale3DEvent.ipp"
#include "event/spatial/Scale4DEvent.ipp"
#include "event/spatial/Size1DEvent.ipp"
#include "event/spatial/Size2DEvent.ipp"
#include "event/spatial/Size3DEvent.ipp"
#include "event/spatial/Size4DEvent.ipp"


#include "event/spatial/meter/MaxSize1MEvent.ipp"
#include "event/spatial/meter/MaxSize2MEvent.ipp"
#include "event/spatial/meter/MaxSize3MEvent.ipp"
#include "event/spatial/meter/MaxSize4MEvent.ipp"
#include "event/spatial/meter/MinSize1MEvent.ipp"
#include "event/spatial/meter/MinSize2MEvent.ipp"
#include "event/spatial/meter/MinSize3MEvent.ipp"
#include "event/spatial/meter/MinSize4MEvent.ipp"
#include "event/spatial/meter/Position1MEvent.ipp"
#include "event/spatial/meter/Position2MEvent.ipp"
#include "event/spatial/meter/Position3MEvent.ipp"
#include "event/spatial/meter/Position4MEvent.ipp"
#include "event/spatial/meter/ScaleMEvent.ipp"
#include "event/spatial/meter/Size1MEvent.ipp"
#include "event/spatial/meter/Size2MEvent.ipp"
#include "event/spatial/meter/Size3MEvent.ipp"
#include "event/spatial/meter/Size4MEvent.ipp"

#include "event/spatial/centimeter/MaxSize1CMEvent.ipp"
#include "event/spatial/centimeter/MaxSize2CMEvent.ipp"
#include "event/spatial/centimeter/MaxSize3CMEvent.ipp"
#include "event/spatial/centimeter/MaxSize4CMEvent.ipp"
#include "event/spatial/centimeter/MinSize1CMEvent.ipp"
#include "event/spatial/centimeter/MinSize2CMEvent.ipp"
#include "event/spatial/centimeter/MinSize3CMEvent.ipp"
#include "event/spatial/centimeter/MinSize4CMEvent.ipp"
#include "event/spatial/centimeter/Position1CMEvent.ipp"
#include "event/spatial/centimeter/Position2CMEvent.ipp"
#include "event/spatial/centimeter/Position3CMEvent.ipp"
#include "event/spatial/centimeter/Position4CMEvent.ipp"
#include "event/spatial/centimeter/ScaleCMEvent.ipp"
#include "event/spatial/centimeter/Size1CMEvent.ipp"
#include "event/spatial/centimeter/Size2CMEvent.ipp"
#include "event/spatial/centimeter/Size3CMEvent.ipp"
#include "event/spatial/centimeter/Size4CMEvent.ipp"
